In [54]:
import pandas as pd
ndf = pd.read_csv('nhappy_0814.csv')

ndf['country']= ndf['country'].astype("category")
ndf['year']= ndf['year'].astype("category")
ndf['country_num']= ndf['country_num'].astype("category")
ndf['continent']= ndf['continent'].astype("category")

from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
x= ndf[['log_gdp', 'social', 'life_exp', 'freedom','generosity', 'corruption', 
       'schooling', 'alcohol', 'suicide','obesity', 'birth', 'mental']]
xnor = MinMaxScaler().fit_transform(x)
dfnor = pd.DataFrame(xnor)
dfnor.columns = ['log_gdp', 'social', 'life_exp', 'freedom', 'generosity', 'corruption', 'schooling', 'alcohol',
                     'suicide','obesity', 'birth', 'mental']

# 정규화 안한 컬럼 dfnor에 추가
dfnor[['HS','year','country','country_num','continent']]= ndf[['HS','year','country','country_num','continent']]
dfnor

,log_gdp,social,life_exp,freedom,generosity,corruption,schooling,alcohol,suicide,obesity,birth,mental,HS,year,country,country_num,continent
0,0.401356,0.809182,0.785714,0.741403,0.333011,0.715190,0.421875,0.269256,0.215085,0.507264,0.206485,0.530582,5.819,2018,Nicaragua,558,Nor.A
1,0.351486,0.566714,0.503571,0.579092,0.363020,0.910338,0.429688,0.075482,0.093262,0.184019,0.479963,0.179361,5.057,2012,Ghana,288,AF
2,0.245562,0.222382,0.397321,0.442916,0.313650,0.796414,0.117188,0.087591,0.065017,0.071025,0.691649,0.086241,3.330,2006,Benin,204,AF
3,0.559545,0.764706,0.774554,0.782669,0.415295,0.853376,0.750000,0.071034,0.525613,0.343019,0.176201,0.493112,4.331,2017,Sri Lanka,144,AS
4,0.315380,0.446198,0.680804,0.766162,0.258470,0.723629,0.304688,0.000365,0.134452,0.135190,0.163047,0.419619,4.633,2015,Bangladesh,50,AS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1876,0.559944,0.880918,0.750446,0.760660,0.253630,0.856540,0.484375,0.002508,0.169182,0.352300,0.138269,0.434382,6.464,2011,Colombia,170,SA
1877,0.379613,0.474892,0.587054,0.757909,0.299129,0.840717,0.375000,0.078060,0.306743,0.143261,0.195626,0.318333,4.424,2014,India,356,AS
1878,0.853980,0.949785,0.888393,0.958735,0.474347,0.154008,0.882812,0.319349,0.164167,0.270379,0.106455,0.515135,7.594,2017,Denmark,208,EU
1879,0.505087,0.846485,0.616071,0.792297,0.583737,0.648734,0.140625,0.056216,0.145703,0.211057,0.154940,0.447314,4.939,2014,Bhutan,64,AS
1880,0.514662,0.771879,0.533482,0.759285,0.140368,0.839662,0.429688,0.085750,0.176421,0.217111,0.366014,0.244110,4.441,2017,Namibia,516,AF

In [ ]:
# 나라 원핫인코딩

In [55]:
df_country = pd.get_dummies(dfnor['country'])
df_country

,Afghanistan,Albania,Algeria,Angola,Argentina,Armenia,Australia,Austria,Azerbaijan,Bahrain,...,United Arab Emirates,United Kingdom,United States,Uruguay,Uzbekistan,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1876,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1877,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1878,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1879,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1880,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [56]:
dfnor = pd.concat([dfnor, df_country], axis=1)
dfnor

,log_gdp,social,life_exp,freedom,generosity,corruption,schooling,alcohol,suicide,obesity,...,United Arab Emirates,United Kingdom,United States,Uruguay,Uzbekistan,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
0,0.401356,0.809182,0.785714,0.741403,0.333011,0.715190,0.421875,0.269256,0.215085,0.507264,...,0,0,0,0,0,0,0,0,0,0
1,0.351486,0.566714,0.503571,0.579092,0.363020,0.910338,0.429688,0.075482,0.093262,0.184019,...,0,0,0,0,0,0,0,0,0,0
2,0.245562,0.222382,0.397321,0.442916,0.313650,0.796414,0.117188,0.087591,0.065017,0.071025,...,0,0,0,0,0,0,0,0,0,0
3,0.559545,0.764706,0.774554,0.782669,0.415295,0.853376,0.750000,0.071034,0.525613,0.343019,...,0,0,0,0,0,0,0,0,0,0
4,0.315380,0.446198,0.680804,0.766162,0.258470,0.723629,0.304688,0.000365,0.134452,0.135190,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1876,0.559944,0.880918,0.750446,0.760660,0.253630,0.856540,0.484375,0.002508,0.169182,0.352300,...,0,0,0,0,0,0,0,0,0,0
1877,0.379613,0.474892,0.587054,0.757909,0.299129,0.840717,0.375000,0.078060,0.306743,0.143261,...,0,0,0,0,0,0,0,0,0,0
1878,0.853980,0.949785,0.888393,0.958735,0.474347,0.154008,0.882812,0.319349,0.164167,0.270379,...,0,0,0,0,0,0,0,0,0,0
1879,0.505087,0.846485,0.616071,0.792297,0.583737,0.648734,0.140625,0.056216,0.145703,0.211057,...,0,0,0,0,0,0,0,0,0,0
1880,0.514662,0.771879,0.533482,0.759285,0.140368,0.839662,0.429688,0.085750,0.176421,0.217111,...,0,0,0,0,0,0,0,0,0,0

In [57]:
dfnor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1881 entries, 0 to 1880
Columns: 170 entries, log_gdp to Zimbabwe
dtypes: category(4), float64(13), uint8(153)
memory usage: 494.6 KB

In [58]:
import pandas as pd
import seaborn as sns
from statsmodels.formula.api import ols
import numpy as np
from scipy import stats
from scipy.stats import norm
import matplotlib.pyplot as plt

# model 1 : country 포함

In [39]:
model1 = ols("np.square(HS)~ country+ log_gdp + social+ life_exp + freedom+ generosity+ corruption+ schooling+ alcohol+ suicide+ obesity+ birth+ mental", data=dfnor)
res1 = model1.fit()
res1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:          np.square(HS)   R-squared:                       0.923
Model:                            OLS   Adj. R-squared:                  0.916
Method:                 Least Squares   F-statistic:                     125.3
Date:                Tue, 17 Aug 2021   Prob (F-statistic):               0.00
Time:                        17:27:54   Log-Likelihood:                -5003.4
No. Observations:                1881   AIC:                         1.034e+04
Df Residuals:                    1716   BIC:                         1.125e+04
Df Model:                         164
Covariance Type:            nonrobust
=======================================================================================================
                                          coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------
Intercept                               3.8209      4.002      0.955      0.340      -4.029      11.671
country[T.Albania]                     -0.2323      2.648     -0.088      0.930      -5.426       4.961
country[T.Algeria]                      3.6627      2.482      1.475      0.140      -1.206       8.531
country[T.Angola]                     -14.1848      2.763     -5.134      0.000     -19.604      -8.766
country[T.Argentina]                    2.1454      2.953      0.726      0.468      -3.647       7.938
country[T.Armenia]                     -1.5153      2.855     -0.531      0.596      -7.114       4.084
country[T.Australia]                    3.7333      4.041      0.924      0.356      -4.193      11.660
country[T.Austria]                      2.9948      3.785      0.791      0.429      -4.429      10.419
country[T.Azerbaijan]                  -2.3324      2.790     -0.836      0.403      -7.806       3.141
country[T.Bahrain]                     -7.7592      3.830     -2.026      0.043     -15.271      -0.247
country[T.Bangladesh]                   3.5253      2.420      1.456      0.145      -1.222       8.273
country[T.Belarus]                      4.9756      4.170      1.193      0.233      -3.204      13.155
country[T.Belgium]                     -0.8825      3.918     -0.225      0.822      -8.566       6.801
country[T.Belize]                      14.9750      3.491      4.290      0.000       8.128      21.822
country[T.Benin]                       -4.6452      1.737     -2.674      0.008      -8.053      -1.238
country[T.Bhutan]                      -9.8863      3.433     -2.880      0.004     -16.619      -3.154
country[T.Bolivia]                      5.8552      2.276      2.573      0.010       1.391      10.319
country[T.Bosnia and Herzegovina]       2.3909      2.830      0.845      0.398      -3.160       7.942
country[T.Botswana]                   -22.7712      2.973     -7.658      0.000     -28.603     -16.939
country[T.Brazil]                      10.9534      2.736      4.003      0.000       5.587      16.320
country[T.Bulgaria]                    -9.2491      3.271     -2.828      0.005     -15.664      -2.834
country[T.Burkina Faso]                -3.1190      1.754     -1.778      0.076      -6.559       0.321
country[T.Burundi]                      7.8382      2.293      3.418      0.001       3.341      12.336
country[T.Cambodia]                    -4.8470      2.311     -2.097      0.036      -9.380      -0.314
country[T.Cameroon]                    -2.2065      1.871     -1.179      0.238      -5.876       1.463
country[T.Canada]                       5.7194      3.829      1.494      0.135      -1.790      13.229
country[T.Central African Republic]     3.5628      2.243      1.589      0.112      -0.836       7.962
country[T.Chad]                        -2.1439      1.678     -1.278      0.201      -5.434       1.146
country[T.Chile]                        4.5646      3.229      1.414      0.158      -1.768      10.897
country[T.China]                       -5.3944      2.764     -1.952      0.051     -10.815       0.026
country[T.Colombia]                     5.5479      2.626      2.113      0.035       0.398      10.698
country[T.Comoros]                     -4.3137      2.087     -2.067      0.039      -8.407      -0.220
country[T.Costa Rica]                  15.5687      2.813      5.535      0.000      10.052      21.085
country[T.Cote d'Ivoire]               -6.8584      2.084     -3.290      0.001     -10.946      -2.770
country[T.Croatia]                     -1.1155      3.218     -0.347      0.729      -7.427       5.196
country[T.Cyprus]                      -1.9614      3.595     -0.546      0.585      -9.012       5.090
country[T.Czechia]                      4.2732      3.537      1.208      0.227      -2.664      11.210
country[T.Denmark]                      7.0381      4.251      1.656      0.098      -1.300      15.376
country[T.Djibouti]                     0.1558      2.584      0.060      0.952      -4.913       5.224
country[T.Dominican Republic]          -7.5756      2.436     -3.110      0.002     -12.354      -2.797
country[T.Ecuador]                      3.9530      2.411      1.640      0.101      -0.776       8.682
country[T.Egypt]                       -3.6994      2.361     -1.567      0.117      -8.330       0.931
country[T.El Salvador]                 15.7630      3.076      5.125      0.000       9.730      21.795
country[T.Estonia]                     -1.9356      3.805     -0.509      0.611      -9.400       5.528
country[T.Eswatini]                   -12.7588      3.298     -3.868      0.000     -19.228      -6.289
country[T.Ethiopia]                     0.4478      2.080      0.215      0.830      -3.631       4.527
country[T.Finland]                      9.2190      3.895      2.367      0.018       1.579      16.859
country[T.France]                      -2.5975      3.965     -0.655      0.512     -10.374       5.178
country[T.Gabon]                      -16.8103      2.680     -6.273      0.000     -22.066     -11.554
country[T.Gambia]                       2.4307      2.455      0.990      0.322      -2.384       7.246
country[T.Georgia]                     -2.3984      2.982     -0.804      0.421      -8.246       3.450
country[T.Germany]                      0.5414      3.985      0.136      0.892      -7.274       8.357
country[T.Ghana]                       -0.9882      1.958     -0.505      0.614      -4.828       2.851
country[T.Greece]                      -3.5010      3.374     -1.038      0.300     -10.119       3.117
country[T.Guatemala]                   12.0366      2.765      4.353      0.000       6.614      17.460
country[T.Guinea]                      -2.4735      1.811     -1.366      0.172      -6.026       1.079
country[T.Haiti]                        3.5712      2.210      1.616      0.106      -0.764       7.906
country[T.Honduras]                     7.9182      2.153      3.678      0.000       3.696      12.140
country[T.Hungary]                     -6.4313      3.557     -1.808      0.071     -13.408       0.546
country[T.Iceland]                      4.8765      4.015      1.215      0.225      -2.998      12.751
country[T.India]                       -4.2652      2.522     -1.691      0.091      -9.211       0.681
country[T.Indonesia]                   -4.2138      2.599     -1.621      0.105      -9.311       0.884
country[T.Iran]                        -5.0341      2.995     -1.681      0.093     -10.909       0.840
country[T.Iraq]                        -6.3275      2.141     -2.956      0.003     -10.526      -2.129
country[T.Ireland]                     -4.3866      4.234     -1.036      0.300     -12.691       3.918
country[T.Israel]                       9.2677      3.723      2.490      0.013       1.966      16.569
country[T.Italy]                       -2.8427      3.514     -0.809      0.419      -9.735       4.049
country[T.Jamaica]                      8.0417      2.680      3.001      0.003       2.786      13.298
country[T.Japan]                      -11.3282      4.334     -2.614      0.009     -19.829      -2.828
country[T.Jordan]                       2.4942      2.498      0.999      0.318      -2.405       7.393
country[T.Kazakhstan]                  -1.7985      3.896     -0.462      0.644      -9.440       5.843
country[T.Kenya]                       -5.4386      2.162     -2.516      0.012      -9.679      -1.199
country[T.Kuwait]                      -7.7435      3.814     -2.031      0.042     -15.223      -0.264
country[T.Kyrgyzstan]                   8.4639      2.789      3.035      0.002       2.994      13.934
country[T.Laos]                        -6.3416      2.349     -2.700      0.007     -10.949      -1.734
country[T.Latvia]                      -1.4316      3.733     -0.384      0.701      -8.753       5.890
country[T.Lebanon]                     -2.4150      2.804     -0.861      0.389      -7.916       3.086
country[T.Lesotho]                     -7.2730      3.089     -2.355      0.019     -13.331      -1.215
country[T.Liberia]                      2.8571      1.872      1.526      0.127      -0.815       6.529
country[T.Libya]                       -0.1373      2.896     -0.047      0.962      -5.817       5.542
country[T.Lithuania]                   -0.4377      3.991     -0.110      0.913      -8.266       7.390
country[T.Luxembourg]                  -9.3300      4.341     -2.149      0.032     -17.845      -0.815
country[T.Madagascar]                   4.3118      2.098      2.055      0.040       0.197       8.427
country[T.Malawi]                       7.3705      1.945      3.789      0.000       3.555      11.186
country[T.Malaysia]                    -4.9792      3.125     -1.594      0.111     -11.108       1.149
country[T.Mali]                        -5.6185      1.775     -3.165      0.002      -9.101      -2.136
country[T.Malta]                       -3.8336      3.399     -1.128      0.259     -10.499       2.832
country[T.Mauritania]                  -7.5688      1.743     -4.341      0.000     -10.988      -4.149
country[T.Mauritius]                    2.0349      3.179      0.640      0.522      -4.201       8.270
country[T.Mexico]                      12.5041      2.547      4.910      0.000       7.509      17.499
country[T.Moldova]                     10.6896      3.305      3.234      0.001       4.207      17.172
country[T.Mongolia]                    -0.6507      3.394     -0.192      0.848      -7.308       6.007
country[T.Montenegro]                  -1.5406      3.043     -0.506      0.613      -7.508       4.427
country[T.Morocco]                      6.2519      2.307      2.710      0.007       1.726      10.777
country[T.Mozambique]                   7.2983      2.020      3.613      0.000       3.336      11.261
country[T.Myanmar]                     -8.9554      2.684     -3.337      0.001     -14.219      -3.691
country[T.Namibia]                    -13.1917      2.692     -4.900      0.000     -18.472      -7.912
country[T.Nepal]                        2.8695      2.388      1.202      0.230      -1.814       7.553
country[T.Netherlands]                  2.8146      4.139      0.680      0.497      -5.304      10.933
country[T.New Zealand]                  4.0534      3.829      1.059      0.290      -3.457      11.564
country[T.Nicaragua]                   11.3380      2.303      4.924      0.000       6.822      15.854
country[T.Niger]                        1.3742      2.058      0.668      0.504      -2.662       5.411
country[T.Nigeria]                     -6.2419      2.231     -2.797      0.005     -10.618      -1.865
country[T.North Macedonia]             -2.8527      2.885     -0.989      0.323      -8.510       2.805
country[T.Norway]                       2.2334      4.284      0.521      0.602      -6.168      10.635
country[T.Pakistan]                     7.3022      1.778      4.107      0.000       3.815      10.790
country[T.Palestine]                    4.3860      2.279      1.924      0.054      -0.084       8.856
country[T.Panama]                       4.1680      2.943      1.416      0.157      -1.604       9.940
country[T.Paraguay]                     1.0208      2.489      0.410      0.682      -3.861       5.902
country[T.Peru]                         2.1207      2.693      0.788      0.431      -3.161       7.402
country[T.Philippines]                  0.0201      2.312      0.009      0.993      -4.515       4.555
country[T.Poland]                      -0.4642      3.550     -0.131      0.896      -7.428       6.499
country[T.Portugal]                   -10.9781      3.345     -3.281      0.001     -17.540      -4.416
country[T.Qatar]                      -15.3705      4.893     -3.141      0.002     -24.968      -5.773
country[T.Romania]                     -0.6352      3.157     -0.201      0.841      -6.828       5.557
country[T.Russia]                      -0.6631      4.124     -0.161      0.872      -8.752       7.426
country[T.Rwanda]                      -5.9459      2.158     -2.756      0.006     -10.178      -1.714
country[T.Saudi Arabia]                -2.2476      3.295     -0.682      0.495      -8.711       4.216
country[T.Senegal]                     -2.8520      1.720     -1.658      0.098      -6.226       0.522
country[T.Serbia]                       0.4603      3.106      0.148      0.882      -5.631       6.552
country[T.Sierra Leone]                -0.4435      1.785     -0.248      0.804      -3.945       3.058
country[T.Singapore]                  -16.2446      4.820     -3.370      0.001     -25.698      -6.791
country[T.Slovakia]                     1.4311      3.476      0.412      0.681      -5.387       8.249
country[T.Slovenia]                    -5.4244      3.659     -1.483      0.138     -12.600       1.752
country[T.South Africa]               -12.0307      3.153     -3.816      0.000     -18.214      -5.847
country[T.South Korea]                -11.4237      5.575     -2.049      0.041     -22.357      -0.490
country[T.Spain]                       -0.7376      3.477     -0.212      0.832      -7.557       6.082
country[T.Sri Lanka]                  -13.9236      3.731     -3.731      0.000     -21.242      -6.605
country[T.Sudan]                       -5.4224      2.113     -2.566      0.010      -9.567      -1.278
country[T.Sweden]                       2.9723      3.966      0.749      0.454      -4.806      10.751
country[T.Switzerland]                  2.4397      4.400      0.554      0.579      -6.191      11.070
country[T.Syria]                       -2.5562      2.193     -1.166      0.244      -6.858       1.745
country[T.Taiwan]                      -9.8492      3.840     -2.565      0.010     -17.381      -2.318
country[T.Tajikistan]                   9.7757      2.562      3.815      0.000       4.750      14.801
country[T.Tanzania]                    -7.1171      1.882     -3.781      0.000     -10.809      -3.425
country[T.Thailand]                    -1.2950      3.068     -0.422      0.673      -7.312       4.722
country[T.Togo]                         3.6636      1.899      1.929      0.054      -0.062       7.389
country[T.Trinidad and Tobago]          2.4366      3.575      0.682      0.496      -4.574       9.448
country[T.Tunisia]                     -0.0277      2.473     -0.011      0.991      -4.877       4.822
country[T.Turkey]                      -6.2570      2.809     -2.228      0.026     -11.765      -0.748
country[T.Turkmenistan]                 2.1170      2.886      0.734      0.463      -3.543       7.777
country[T.Uganda]                      -2.3408      2.064     -1.134      0.257      -6.389       1.708
country[T.Ukraine]                      1.4828      3.621      0.409      0.682      -5.619       8.585
country[T.United Arab Emirates]        -5.5866      3.907     -1.430      0.153     -13.250       2.076
country[T.United Kingdom]              -0.5057      3.875     -0.130      0.896      -8.106       7.095
country[T.United States]                2.4085      3.893      0.619      0.536      -5.228      10.045
country[T.Uruguay]                      0.2791      2.883      0.097      0.923      -5.375       5.933
country[T.Uzbekistan]                   9.7077      2.844      3.414      0.001       4.130      15.285
country[T.Venezuela]                    7.3347      2.627      2.792      0.005       2.181      12.488
country[T.Vietnam]                      0.6866      2.768      0.248      0.804      -4.742       6.115
country[T.Yemen]                       -4.6312      1.721     -2.692      0.007      -8.006      -1.257
country[T.Zambia]                      -3.6306      2.175     -1.669      0.095      -7.897       0.636
country[T.Zimbabwe]                    -5.2379      2.621     -1.999      0.046     -10.378      -0.097
log_gdp                                59.8916      4.734     12.652      0.000      50.607      69.176
social                                 10.9991      1.328      8.285      0.000       8.395      13.603
life_exp                               -9.2771      3.871     -2.397      0.017     -16.869      -1.685
freedom                                 5.9925      0.964      6.218      0.000       4.102       7.883
generosity                              4.0796      1.247      3.271      0.001       1.633       6.526
corruption                             -5.5946      1.410     -3.967      0.000      -8.361      -2.828
schooling                              -5.8410      3.990     -1.464      0.143     -13.666       1.984
alcohol                                -9.4483      3.919     -2.411      0.016     -17.134      -1.762
suicide                                 6.6304      4.762      1.392      0.164      -2.710      15.970
obesity                               -13.7419      4.564     -3.011      0.003     -22.693      -4.790
birth                                   6.0715      3.843      1.580      0.114      -1.466      13.610
mental                                 -2.7362      4.692     -0.583      0.560     -11.939       6.467
==============================================================================
Omnibus:                       54.556   Durbin-Watson:                   2.037
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               93.407
Skew:                           0.238   Prob(JB):                     5.21e-21
Kurtosis:                       3.982   Cond. No.                         758.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

## X, y 데이터 분리

In [59]:
X_data = dfnor.drop(['HS','year','country','country_num','continent'], axis = 1)
y = dfnor[['HS']]

X_data.head()

,log_gdp,social,life_exp,freedom,generosity,corruption,schooling,alcohol,suicide,obesity,...,United Arab Emirates,United Kingdom,United States,Uruguay,Uzbekistan,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
0,0.401356,0.809182,0.785714,0.741403,0.333011,0.715190,0.421875,0.269256,0.215085,0.507264,...,0,0,0,0,0,0,0,0,0,0
1,0.351486,0.566714,0.503571,0.579092,0.363020,0.910338,0.429688,0.075482,0.093262,0.184019,...,0,0,0,0,0,0,0,0,0,0
2,0.245562,0.222382,0.397321,0.442916,0.313650,0.796414,0.117188,0.087591,0.065017,0.071025,...,0,0,0,0,0,0,0,0,0,0
3,0.559545,0.764706,0.774554,0.782669,0.415295,0.853376,0.750000,0.071034,0.525613,0.343019,...,0,0,0,0,0,0,0,0,0,0
4,0.315380,0.446198,0.680804,0.766162,0.258470,0.723629,0.304688,0.000365,0.134452,0.135190,...,0,0,0,0,0,0,0,0,0,0

## train, test 데이터 분리

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X_data, y_target,
                                                  test_size=0.3, random_state=4)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(1316, 165)
(1316, 1)
(565, 165)
(565, 1)

## 1. Linear Regression

In [42]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_train = lr.predict(X_train)
y_pred_test = lr.predict(X_test)

train_mse = mean_squared_error(y_train, y_pred_train)
train_rmse = np.sqrt(train_mse)

test_mse = mean_squared_error(y_test, y_pred_test)
test_rmse = np.sqrt(test_mse)

print('lr.coef_: {}'.format(lr.coef_))
print('Train MSE:{0:.3f}, RMSE:{1:3.3F}'.format(train_mse, train_rmse))
print('Train Variance score: {0:.3f}'.format(r2_score(y_train, y_pred_train)))
print('Test MSE:{0:.3f}, RMSE:{1:3.3F}'.format(test_mse, test_rmse))
print('Test Variance score: {0:.3f}'.format(r2_score(y_test, y_pred_test)))

lr.coef_: [[ 5.68866818e+00  1.24817854e+00 -6.67942988e-01  6.37224601e-01
   3.15810159e-01 -3.04588380e-01 -2.10787058e-01 -8.42809113e-01
   1.19915591e+00 -1.34881594e+00  1.23242635e+00 -3.59076995e-01
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11  2.87768801e+11  2.87768801e+11  2.87768801e+11
   2.87768801e+11]]
Train MSE:0.106, RMSE:0.325
Train Variance score: 0.916
Test MSE:0.153, RMSE:0.391
Test Variance score: 0.878

## 2. Ridge Regression

In [61]:
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge
from sklearn.model_selection import cross_val_score
ridge = Ridge(random_state=4)

cv_method = KFold(n_splits=10)
params = {
    'alpha': [0.001, 0.005, 0.01, 0.015, 0.1, 1, 10]
}
dt_grid_cv = GridSearchCV(ridge, param_grid=params, scoring='neg_mean_squared_error', cv=cv_method, n_jobs=-1)
dt_grid_cv.fit(X_train, y_train)

y_pred_test = dt_grid_cv.predict(X_test)
test_mse = mean_squared_error(y_test, y_pred_test)
test_rmse = np.sqrt(test_mse)

neg_mse = dt_grid_cv.best_score_
mse = -1 * neg_mse
rmse = np.sqrt(mse)

print(dt_grid_cv.best_params_)
print(dt_grid_cv.best_score_)
print(rmse)
print(test_rmse)

{'alpha': 0.1}
-0.14025719008940585
0.37450926569232684
0.39111393469538003

## 3. Lasso Regression

In [62]:
from sklearn.linear_model import Lasso
lasso = Lasso(random_state=4)

cv_method = KFold(n_splits=10)
params = {
    'alpha': [0.0001, 0.005, 0.01, 0.1, 1, 10]
}
dt_grid_cv = GridSearchCV(lasso, param_grid=params, scoring='neg_mean_squared_error', cv=cv_method, n_jobs=-1)
dt_grid_cv.fit(X_train, y_train)

y_pred_test = dt_grid_cv.predict(X_test)
test_mse = mean_squared_error(y_test, y_pred_test)
test_rmse = np.sqrt(test_mse)

neg_mse = dt_grid_cv.best_score_
mse = -1 * neg_mse
rmse = np.sqrt(mse)

print(dt_grid_cv.best_params_)
print(dt_grid_cv.best_score_)
print(rmse)
print(test_rmse)

{'alpha': 0.0001}
-0.1395883018875552
0.3736151788773513
0.39163181020107013

## 4. ElasticNet Regression

In [63]:
from sklearn.linear_model import ElasticNet

elasticnet = ElasticNet(random_state=4)

cv_method = KFold(n_splits=10)
params = {
    'alpha': [0.0001, 0.005, 0.01, 0.1, 1, 10]
}
dt_grid_cv = GridSearchCV(elasticnet, param_grid=params, scoring='neg_mean_squared_error', cv=cv_method, n_jobs=-1)
dt_grid_cv.fit(X_train, y_train)

y_pred_test = dt_grid_cv.predict(X_test)
test_mse = mean_squared_error(y_test, y_pred_test)
test_rmse = np.sqrt(test_mse)

neg_mse = dt_grid_cv.best_score_
mse = -1 * neg_mse
rmse = np.sqrt(mse)

print(dt_grid_cv.best_params_)
print(dt_grid_cv.best_score_)
print(rmse)
print(test_rmse)

{'alpha': 0.0001}
-0.13979725436211482
0.37389471026228066
0.391385079918207

## MODEL 2 : CONTINENT 포함

In [65]:
import pandas as pd
ndf = pd.read_csv('nhappy_0814.csv')

ndf['country']= ndf['country'].astype("category")
ndf['year']= ndf['year'].astype("category")
ndf['country_num']= ndf['country_num'].astype("category")
ndf['continent']= ndf['continent'].astype("category")

from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
x= ndf[['log_gdp', 'social', 'life_exp', 'freedom','generosity', 'corruption', 
       'schooling', 'alcohol', 'suicide','obesity', 'birth', 'mental']]
xnor = MinMaxScaler().fit_transform(x)
dfnor = pd.DataFrame(xnor)
dfnor.columns = ['log_gdp', 'social', 'life_exp', 'freedom', 'generosity', 'corruption', 'schooling', 'alcohol',
                     'suicide','obesity', 'birth', 'mental']

# 정규화 안한 컬럼 dfnor에 추가
dfnor[['HS','year','country','country_num','continent']]= ndf[['HS','year','country','country_num','continent']]
dfnor

,log_gdp,social,life_exp,freedom,generosity,corruption,schooling,alcohol,suicide,obesity,birth,mental,HS,year,country,country_num,continent
0,0.401356,0.809182,0.785714,0.741403,0.333011,0.715190,0.421875,0.269256,0.215085,0.507264,0.206485,0.530582,5.819,2018,Nicaragua,558,Nor.A
1,0.351486,0.566714,0.503571,0.579092,0.363020,0.910338,0.429688,0.075482,0.093262,0.184019,0.479963,0.179361,5.057,2012,Ghana,288,AF
2,0.245562,0.222382,0.397321,0.442916,0.313650,0.796414,0.117188,0.087591,0.065017,0.071025,0.691649,0.086241,3.330,2006,Benin,204,AF
3,0.559545,0.764706,0.774554,0.782669,0.415295,0.853376,0.750000,0.071034,0.525613,0.343019,0.176201,0.493112,4.331,2017,Sri Lanka,144,AS
4,0.315380,0.446198,0.680804,0.766162,0.258470,0.723629,0.304688,0.000365,0.134452,0.135190,0.163047,0.419619,4.633,2015,Bangladesh,50,AS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1876,0.559944,0.880918,0.750446,0.760660,0.253630,0.856540,0.484375,0.002508,0.169182,0.352300,0.138269,0.434382,6.464,2011,Colombia,170,SA
1877,0.379613,0.474892,0.587054,0.757909,0.299129,0.840717,0.375000,0.078060,0.306743,0.143261,0.195626,0.318333,4.424,2014,India,356,AS
1878,0.853980,0.949785,0.888393,0.958735,0.474347,0.154008,0.882812,0.319349,0.164167,0.270379,0.106455,0.515135,7.594,2017,Denmark,208,EU
1879,0.505087,0.846485,0.616071,0.792297,0.583737,0.648734,0.140625,0.056216,0.145703,0.211057,0.154940,0.447314,4.939,2014,Bhutan,64,AS
1880,0.514662,0.771879,0.533482,0.759285,0.140368,0.839662,0.429688,0.085750,0.176421,0.217111,0.366014,0.244110,4.441,2017,Namibia,516,AF

In [77]:
model2 = ols("np.square(HS)~ continent+ log_gdp + social+ life_exp + freedom+ generosity+ corruption+ schooling+ alcohol+ suicide+ obesity+ birth+ mental", data=dfnor)
res2 = model2.fit()
res2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:          np.square(HS)   R-squared:                       0.814
Model:                            OLS   Adj. R-squared:                  0.812
Method:                 Least Squares   F-statistic:                     478.3
Date:                Tue, 17 Aug 2021   Prob (F-statistic):               0.00
Time:                        17:41:16   Log-Likelihood:                -5833.9
No. Observations:                1881   AIC:                         1.170e+04
Df Residuals:                    1863   BIC:                         1.180e+04
Df Model:                          17
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             -9.5221      1.891     -5.036      0.000     -13.230      -5.814
continent[T.AS]        1.3711      0.496      2.763      0.006       0.398       2.344
continent[T.EU]        4.3099      0.678      6.352      0.000       2.979       5.641
continent[T.Nor.A]     9.0211      0.665     13.558      0.000       7.716      10.326
continent[T.OC]        6.3002      1.239      5.085      0.000       3.870       8.730
continent[T.SA]        7.7305      0.662     11.685      0.000       6.433       9.028
log_gdp               30.5554      1.537     19.884      0.000      27.542      33.569
social                10.7519      1.150      9.346      0.000       8.496      13.008
life_exp              11.0239      2.198      5.014      0.000       6.712      15.336
freedom                6.9382      0.858      8.089      0.000       5.256       8.620
generosity             7.5365      0.974      7.740      0.000       5.627       9.446
corruption            -7.1085      0.849     -8.377      0.000      -8.773      -5.444
schooling              1.7851      1.061      1.683      0.093      -0.295       3.865
alcohol                4.6450      1.175      3.952      0.000       2.340       6.950
suicide               -4.4590      1.392     -3.203      0.001      -7.189      -1.729
obesity               -7.8470      0.986     -7.961      0.000      -9.780      -5.914
birth                 13.5701      1.436      9.450      0.000      10.754      16.386
mental                 5.4303      1.538      3.530      0.000       2.413       8.447
==============================================================================
Omnibus:                        5.966   Durbin-Watson:                   2.060
Prob(Omnibus):                  0.051   Jarque-Bera (JB):                7.233
Skew:                          -0.003   Prob(JB):                       0.0269
Kurtosis:                       3.304   Cond. No.                         49.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [66]:
# continent 원핫인코딩
df_continent = pd.get_dummies(dfnor['continent'])
df_continent

      AF  AS  EU  Nor.A  OC  SA
0      0   0   0      1   0   0
1      1   0   0      0   0   0
2      1   0   0      0   0   0
3      0   1   0      0   0   0
4      0   1   0      0   0   0
...   ..  ..  ..    ...  ..  ..
1876   0   0   0      0   0   1
1877   0   1   0      0   0   0
1878   0   0   1      0   0   0
1879   0   1   0      0   0   0
1880   1   0   0      0   0   0

[1881 rows x 6 columns]

In [67]:
dfnor = pd.concat([dfnor, df_continent], axis=1)
dfnor

,log_gdp,social,life_exp,freedom,generosity,corruption,schooling,alcohol,suicide,obesity,...,year,country,country_num,continent,AF,AS,EU,Nor.A,OC,SA
0,0.401356,0.809182,0.785714,0.741403,0.333011,0.715190,0.421875,0.269256,0.215085,0.507264,...,2018,Nicaragua,558,Nor.A,0,0,0,1,0,0
1,0.351486,0.566714,0.503571,0.579092,0.363020,0.910338,0.429688,0.075482,0.093262,0.184019,...,2012,Ghana,288,AF,1,0,0,0,0,0
2,0.245562,0.222382,0.397321,0.442916,0.313650,0.796414,0.117188,0.087591,0.065017,0.071025,...,2006,Benin,204,AF,1,0,0,0,0,0
3,0.559545,0.764706,0.774554,0.782669,0.415295,0.853376,0.750000,0.071034,0.525613,0.343019,...,2017,Sri Lanka,144,AS,0,1,0,0,0,0
4,0.315380,0.446198,0.680804,0.766162,0.258470,0.723629,0.304688,0.000365,0.134452,0.135190,...,2015,Bangladesh,50,AS,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1876,0.559944,0.880918,0.750446,0.760660,0.253630,0.856540,0.484375,0.002508,0.169182,0.352300,...,2011,Colombia,170,SA,0,0,0,0,0,1
1877,0.379613,0.474892,0.587054,0.757909,0.299129,0.840717,0.375000,0.078060,0.306743,0.143261,...,2014,India,356,AS,0,1,0,0,0,0
1878,0.853980,0.949785,0.888393,0.958735,0.474347,0.154008,0.882812,0.319349,0.164167,0.270379,...,2017,Denmark,208,EU,0,0,1,0,0,0
1879,0.505087,0.846485,0.616071,0.792297,0.583737,0.648734,0.140625,0.056216,0.145703,0.211057,...,2014,Bhutan,64,AS,0,1,0,0,0,0
1880,0.514662,0.771879,0.533482,0.759285,0.140368,0.839662,0.429688,0.085750,0.176421,0.217111,...,2017,Namibia,516,AF,1,0,0,0,0,0

## X, y 데이터 분리

In [71]:
X_data = dfnor.drop(['HS','year','country','country_num','continent'], axis = 1)
y = dfnor[['HS']]

X_data.head()

,log_gdp,social,life_exp,freedom,generosity,corruption,schooling,alcohol,suicide,obesity,birth,mental,AF,AS,EU,Nor.A,OC,SA
0,0.401356,0.809182,0.785714,0.741403,0.333011,0.715190,0.421875,0.269256,0.215085,0.507264,0.206485,0.530582,0,0,0,1,0,0
1,0.351486,0.566714,0.503571,0.579092,0.363020,0.910338,0.429688,0.075482,0.093262,0.184019,0.479963,0.179361,1,0,0,0,0,0
2,0.245562,0.222382,0.397321,0.442916,0.313650,0.796414,0.117188,0.087591,0.065017,0.071025,0.691649,0.086241,1,0,0,0,0,0
3,0.559545,0.764706,0.774554,0.782669,0.415295,0.853376,0.750000,0.071034,0.525613,0.343019,0.176201,0.493112,0,1,0,0,0,0
4,0.315380,0.446198,0.680804,0.766162,0.258470,0.723629,0.304688,0.000365,0.134452,0.135190,0.163047,0.419619,0,1,0,0,0,0

## train, test 데이터 분리

In [72]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X_data, y_target,
                                                  test_size=0.3, random_state=4)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(1316, 18)
(1316, 1)
(565, 18)
(565, 1)

## 1. Linear Regression

In [73]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_train = lr.predict(X_train)
y_pred_test = lr.predict(X_test)

train_mse = mean_squared_error(y_train, y_pred_train)
train_rmse = np.sqrt(train_mse)

test_mse = mean_squared_error(y_test, y_pred_test)
test_rmse = np.sqrt(test_mse)

print('lr.coef_: {}'.format(lr.coef_))
print('Train MSE:{0:.3f}, RMSE:{1:3.3F}'.format(train_mse, train_rmse))
print('Train Variance score: {0:.3f}'.format(r2_score(y_train, y_pred_train)))
print('Test MSE:{0:.3f}, RMSE:{1:3.3F}'.format(test_mse, test_rmse))
print('Test Variance score: {0:.3f}'.format(r2_score(y_test, y_pred_test)))

lr.coef_: [[ 2.63252215  1.24957338  1.14717676  0.66744971  0.54333486 -0.42525415
  -0.04228437  0.44888863 -0.2941654  -0.53353524  1.1352664   0.46008851
  -0.46948225 -0.27537408 -0.05057957  0.35434289  0.10143165  0.33966137]]
Train MSE:0.243, RMSE:0.493
Train Variance score: 0.808
Test MSE:0.259, RMSE:0.509
Test Variance score: 0.792

## 2. Ridge Regression

In [74]:
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge
from sklearn.model_selection import cross_val_score
ridge = Ridge(random_state=4)

cv_method = KFold(n_splits=10)
params = {
    'alpha': [0.001, 0.005, 0.01, 0.015, 0.1, 1, 10]
}
dt_grid_cv = GridSearchCV(ridge, param_grid=params, scoring='neg_mean_squared_error', cv=cv_method, n_jobs=-1)
dt_grid_cv.fit(X_train, y_train)

y_pred_test = dt_grid_cv.predict(X_test)
test_mse = mean_squared_error(y_test, y_pred_test)
test_rmse = np.sqrt(test_mse)

neg_mse = dt_grid_cv.best_score_
mse = -1 * neg_mse
rmse = np.sqrt(mse)

print(dt_grid_cv.best_params_)
print(dt_grid_cv.best_score_)
print(rmse)
print(test_rmse)

{'alpha': 0.1}
-0.25002723561305007
0.5000272348713118
0.508879082220966

## 3. Lasso Regression

In [75]:
from sklearn.linear_model import Lasso
lasso = Lasso(random_state=4)

cv_method = KFold(n_splits=10)
params = {
    'alpha': [0.0001, 0.005, 0.01, 0.1, 1, 10]
}
dt_grid_cv = GridSearchCV(lasso, param_grid=params, scoring='neg_mean_squared_error', cv=cv_method, n_jobs=-1)
dt_grid_cv.fit(X_train, y_train)

y_pred_test = dt_grid_cv.predict(X_test)
test_mse = mean_squared_error(y_test, y_pred_test)
test_rmse = np.sqrt(test_mse)

neg_mse = dt_grid_cv.best_score_
mse = -1 * neg_mse
rmse = np.sqrt(mse)

print(dt_grid_cv.best_params_)
print(dt_grid_cv.best_score_)
print(rmse)
print(test_rmse)

{'alpha': 0.0001}
-0.25005334962366
0.5000533467777812
0.5087843229715936

## 4. ElasticNet Regression

In [76]:
from sklearn.linear_model import ElasticNet

elasticnet = ElasticNet(random_state=4)

cv_method = KFold(n_splits=10)
params = {
    'alpha': [0.0001, 0.005, 0.01, 0.1, 1, 10]
}
dt_grid_cv = GridSearchCV(elasticnet, param_grid=params, scoring='neg_mean_squared_error', cv=cv_method, n_jobs=-1)
dt_grid_cv.fit(X_train, y_train)

y_pred_test = dt_grid_cv.predict(X_test)
test_mse = mean_squared_error(y_test, y_pred_test)
test_rmse = np.sqrt(test_mse)

neg_mse = dt_grid_cv.best_score_
mse = -1 * neg_mse
rmse = np.sqrt(mse)

print(dt_grid_cv.best_params_)
print(dt_grid_cv.best_score_)
print(rmse)
print(test_rmse)

{'alpha': 0.0001}
-0.2500340067295821
0.5000340055732031
0.5088393106728601

# 결론 

## model1 (country 포함) 
#### - R^2 : 0.923
#### - test 데이터 RMSE : 약 0.39 


## model2 (continent 포함) 
#### - R^2 : 0.814
#### - test 데이터 RMSE : 약 0.51